# This workflow will lint Python code using flake8
# NOTE: ALL ERRORS ARE SET TO WARNING LEVEL AND WILL NOT DISABLE GITHUB MERGE

name: Lint with Flake8

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: linting
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings (Delete if error level is needed). Python line length recomended by 
        flake8 pycognaize --count --max-complexity=10 --max-line-length=79 --statistics --exclude "*tests/*","*temp/*"
